In [1]:
import pandas as pd
import seaborn as sns

In [2]:
data = pd.read_csv('US_Accidents_March23.csv')

In [3]:
data.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Description',
       'Street', 'City', 'County', 'State', 'Zipcode', 'Country', 'Timezone',
       'Airport_Code', 'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)',
       'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Direction',
       'Wind_Speed(mph)', 'Precipitation(in)', 'Weather_Condition', 'Amenity',
       'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway',
       'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal',
       'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

# Quantitative - Discrete
- Severity

# Quantitative - Continuous
- Start Time
- End Time
- Start Lat
- Start Long
- End Lat
- End Long
- Distance
- Weather Time Stamp - verify temporal proximity to start time
- Temperature
- Wind Chill
- Humidity(%)
- Pressure(in)
- Visibility(mi)
- Wind_Speed(mph)
- Precipitation(in)

# Qualitative - Binary
- Amenity
- Bump
- Crossing
- Give_Way
- Junction
- No_Exit
- Railway
- Roundabout
- Station
- Stop
- Traffic_Calming
- Traffic_Signal
- Turning_Loop

# Qualitiative - Categorical
- County City State Combo?
- State
- Zipcode: remove last 4 digits? - categorize urban, rural, other
- Country - check if all US - remove others
- Timezone
- Airport code - where weather info came from
- Wind_Direction
- Weather_Condition
- Sunrise_Sunset
- Civil_Twilight
- Nautical_Twilight
- Astronomical_Twilight

# Qualitative - Text?
- Description
- Street
- City
- County

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7728394 entries, 0 to 7728393
Data columns (total 46 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     object
 1   Source                 object
 2   Severity               int64
 3   Start_Time             object
 4   End_Time               object
 5   Start_Lat              float64
 6   Start_Lng              float64
 7   End_Lat                float64
 8   End_Lng                float64
 9   Distance(mi)           float64
 10  Description            object
 11  Street                 object
 12  City                   object
 13  County                 object
 14  State                  object
 15  Zipcode                object
 16  Country                object
 17  Timezone               object
 18  Airport_Code           object
 19  Weather_Timestamp      object
 20  Temperature(F)         float64
 21  Wind_Chill(F)          float64
 22  Humidity(%)            float64
 23  Pressure(in)           float64
 24  Visibility(mi)         float64
 25  Wind_Direction         object
 26  Wind_Speed(mph)        float64
 27  Precipitation(in)      float64
 28  Weather_Condition      object
 29  Amenity                bool
 30  Bump                   bool
 31  Crossing               bool
 32  Give_Way               bool
 33  Junction               bool
 34  No_Exit                bool
 35  Railway                bool
 36  Roundabout             bool
 37  Station                bool
 38  Stop                   bool
 39  Traffic_Calming        bool
 40  Traffic_Signal         bool
 41  Turning_Loop           bool
 42  Sunrise_Sunset         object
 43  Civil_Twilight         object
 44  Nautical_Twilight      object
 45  Astronomical_Twilight  object
dtypes: bool(13), float64(12), int64(1), object(20)
memory usage: 2.0+ GB

In [5]:
data.dtypes

ID                        object
Source                    object
Severity                   int64
Start_Time                object
End_Time                  object
Start_Lat                float64
Start_Lng                float64
End_Lat                  float64
End_Lng                  float64
Distance(mi)             float64
Description               object
Street                    object
City                      object
County                    object
State                     object
Zipcode                   object
Country                   object
Timezone                  object
Airport_Code              object
Weather_Timestamp         object
Temperature(F)           float64
Wind_Chill(F)            float64
Humidity(%)              float64
Pressure(in)             float64
Visibility(mi)           float64
Wind_Direction            object
Wind_Speed(mph)          float64
Precipitation(in)        float64
Weather_Condition         object
Amenity                     bool
Bump                        bool
Crossing                    bool
Give_Way                    bool
Junction                    bool
No_Exit                     bool
Railway                     bool
Roundabout                  bool
Station                     bool
Stop                        bool
Traffic_Calming             bool
Traffic_Signal              bool
Turning_Loop                bool
Sunrise_Sunset            object
Civil_Twilight            object
Nautical_Twilight         object
Astronomical_Twilight     object
dtype: object

In [6]:
data.describe()

,Severity,Start_Lat,Start_Lng,End_Lat,End_Lng,Distance(mi),Temperature(F),Wind_Chill(F),Humidity(%),Pressure(in),Visibility(mi),Wind_Speed(mph),Precipitation(in)
count,7.728394e+06,7.728394e+06,7.728394e+06,4.325632e+06,4.325632e+06,7.728394e+06,7.564541e+06,5.729375e+06,7.554250e+06,7.587715e+06,7.551296e+06,7.157161e+06,5.524808e+06
mean,2.212384e+00,3.620119e+01,-9.470255e+01,3.626183e+01,-9.572557e+01,5.618423e-01,6.166329e+01,5.825105e+01,6.483104e+01,2.953899e+01,9.090376e+00,7.685490e+00,8.407210e-03
std,4.875313e-01,5.076079e+00,1.739176e+01,5.272905e+00,1.810793e+01,1.776811e+00,1.901365e+01,2.238983e+01,2.282097e+01,1.006190e+00,2.688316e+00,5.424983e+00,1.102246e-01
min,1.000000e+00,2.455480e+01,-1.246238e+02,2.456601e+01,-1.245457e+02,0.000000e+00,-8.900000e+01,-8.900000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.000000e+00,3.339963e+01,-1.172194e+02,3.346207e+01,-1.177543e+02,0.000000e+00,4.900000e+01,4.300000e+01,4.800000e+01,2.937000e+01,1.000000e+01,4.600000e+00,0.000000e+00
50%,2.000000e+00,3.582397e+01,-8.776662e+01,3.618349e+01,-8.802789e+01,3.000000e-02,6.400000e+01,6.200000e+01,6.700000e+01,2.986000e+01,1.000000e+01,7.000000e+00,0.000000e+00
75%,2.000000e+00,4.008496e+01,-8.035368e+01,4.017892e+01,-8.024709e+01,4.640000e-01,7.600000e+01,7.500000e+01,8.400000e+01,3.003000e+01,1.000000e+01,1.040000e+01,0.000000e+00
max,4.000000e+00,4.900220e+01,-6.711317e+01,4.907500e+01,-6.710924e+01,4.417500e+02,2.070000e+02,2.070000e+02,1.000000e+02,5.863000e+01,1.400000e+02,1.087000e+03,3.647000e+01

In [7]:
binary_columns = ['Amenity','Bump', 'Crossing', 'Give_Way' ,'Junction','No_Exit', 'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop']

categorical_columns = ['County', 'City', 'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Wind_Direction', 
                       'Weather_Condition', 'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight']

discrete_columns = ['Severity']

quantitative_col = ['Start_Time','End_Time', 'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)', 'Weather_Timestamp', 'Temperature(F)', 
                    'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)', 'Visibility(mi)', 'Wind_Speed(mph)', 'Precipitation(in)']

In [8]:
def cat_col(df, col):
    print("********************************************************************************************************")
    print(df[col].value_counts(dropna=False))

def quant_col(df, col):
    print("********************************************************************************************************")
    sns.boxplot(data = data[col], orient = 'h')

In [9]:
[cat_col(data, i) for i in binary_columns]

********************************************************************************************************
Amenity
False    7632060
True       96334
Name: count, dtype: int64
********************************************************************************************************
Bump
False    7724880
True        3514
Name: count, dtype: int64
********************************************************************************************************
Crossing
False    6854631
True      873763
Name: count, dtype: int64
********************************************************************************************************
Give_Way
False    7691812
True       36582
Name: count, dtype: int64
********************************************************************************************************
Junction
False    7157052
True      571342
Name: count, dtype: int64
********************************************************************************************************
No_Exit
False    7708849
True       19545
Name: count, dtype: int64
********************************************************************************************************
Railway
False    7661415
True       66979
Name: count, dtype: int64
********************************************************************************************************
Roundabout
False    7728145
True         249
Name: count, dtype: int64
********************************************************************************************************
Station
False    7526493
True      201901
Name: count, dtype: int64
********************************************************************************************************
Stop
False    7514023
True      214371
Name: count, dtype: int64
********************************************************************************************************
Traffic_Calming
False    7720796
True        7598
Name: count, dtype: int64
********************************************************************************************************
Traffic_Signal
False    6584622
True     1143772
Name: count, dtype: int64
********************************************************************************************************
Turning_Loop
False    7728394
Name: count, dtype: int64

[None, None, None, None, None, None, None, None, None, None, None, None, None]

In [10]:
[cat_col(data, i) for i in categorical_columns]

********************************************************************************************************
County
Los Angeles        526851
Miami-Dade         251601
Orange             241275
Harris             181196
Dallas             157024
                    ...
Mclean                  1
Poquoson (City)         1
Dewitt                  1
Frontier                1
Ness                    1
Name: count, Length: 1871, dtype: int64
********************************************************************************************************
City
Miami                           186917
Houston                         169609
Los Angeles                     156491
Charlotte                       138652
Dallas                          130939
                                 ...
Villa Grande                         1
Northeast Travis                     1
Miromar Lakes                        1
Pewee Valley                         1
American Fork-Pleasant Grove         1
Name: count, Length: 13679, dtype: int64
********************************************************************************************************
State
CA    1741433
FL     880192
TX     582837
SC     382557
NY     347960
NC     338199
VA     303301
PA     296620
MN     192084
OR     179660
AZ     170609
GA     169234
IL     168958
TN     167388
MI     162191
LA     149701
NJ     140719
MD     140417
OH     118115
WA     108221
AL     101044
UT      97079
CO      90885
OK      83647
MO      77323
CT      71005
IN      67224
MA      61996
WI      34688
KY      32254
NE      28870
MT      28496
IA      26307
AR      22780
NV      21665
KS      20992
DC      18630
RI      16971
MS      15181
DE      14097
WV      13793
ID      11376
NM      10325
NH      10213
WY       3757
ND       3487
ME       2698
VT        926
SD        289
Name: count, dtype: int64
********************************************************************************************************
Zipcode
91761         11247
91706         10022
92407          8922
92507          8850
33186          8375
              ...
29349-9729        1
27263-8819        1
28208-2854        1
24416-1269        1
94401-2213        1
Name: count, Length: 825095, dtype: int64
********************************************************************************************************
Country
US    7728394
Name: count, dtype: int64
********************************************************************************************************
Timezone
US/Eastern     3580167
US/Pacific     2062984
US/Central     1645616
US/Mountain     431819
NaN               7808
Name: count, dtype: int64
********************************************************************************************************
Airport_Code
KCQT    118332
KRDU    107267
KMCJ    101786
KBNA     98926
KCLT     97273
         ...
KP58         1
KWRL         1
KMRH         1
K7R5         1
KICR         1
Name: count, Length: 2046, dtype: int64
********************************************************************************************************
Wind_Direction
CALM        961624
S           419989
SSW         384840
W           383913
WNW         378781
NW          369352
Calm        368557
SW          364470
WSW         353806
SSE         349110
NNW         333427
N           307151
SE          294901
E           278914
ESE         268311
NE          258639
ENE         258474
NNE         255311
VAR         250566
South       177375
NaN         175206
West        164751
North       153385
Variable    113996
East        103545
Name: count, dtype: int64
********************************************************************************************************
Weather_Condition
Fair                           2560802
Mostly Cloudy                  1016195
Cloudy                          817082
Clear                           808743
Partly Cloudy                   698972
                                ...
Sand / Windy                         1
Heavy Rain Shower / Windy            1
Blowing Snow Nearby                  1
Heavy Freezing Rain / Windy          1
Drifting Snow                        1
Name: count, Length: 145, dtype: int64
********************************************************************************************************
Sunrise_Sunset
Day      5334553
Night    2370595
NaN        23246
Name: count, dtype: int64
********************************************************************************************************
Civil_Twilight
Day      5695619
Night    2009529
NaN        23246
Name: count, dtype: int64
********************************************************************************************************
Nautical_Twilight
Day      6076156
Night    1628992
NaN        23246
Name: count, dtype: int64
********************************************************************************************************
Astronomical_Twilight
Day      6377548
Night    1327600
NaN        23246
Name: count, dtype: int64

[None, None, None, None, None, None, None, None, None, None, None, None, None]

In [11]:
[cat_col(data, i) for i in discrete_columns]

********************************************************************************************************
Severity
2    6156981
3    1299337
4     204710
1      67366
Name: count, dtype: int64

[None]

In [ ]:
sns.boxplot(data = data['Start_Time'], orient = 'h')

In [ ]:
sns.boxplot(data = data['End_Time'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Start_Lat'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Start_Lng'], orient = 'h')

In [ ]:
sns.boxplot(data = data['End_Lat'], orient = 'h')

In [ ]:
sns.boxplot(data = data['End_Lng'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Distance(mi)'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Weather_Timestamp'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Temperature(F)'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Wind_Chill(F)'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Humidity(%)'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Pressure(in)'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Visibility(mi)'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Wind_Speed(mph)'], orient = 'h')

In [ ]:
sns.boxplot(data = data['Precipitation(in)'], orient = 'h')

# Ideas
- Remove based off NAs
- See if we should clean categorical data (illinois, IL to Illinois)
- Keep only one: time, sunset, civil_twi, naut_twi, astro_twi
- Find correlation between each column and Severity - see if any factors can be eliminated
- NLP description (ind) with Severity (dep) - Multinomial Naive Bayes